/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencia_de_aviacion;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel
 */
public class Añadirvuelo extends javax.swing.JPanel {

    /**
     * Creates new form Añadirvuelo
     */
     Fuente f=new Fuente();
  java.util.Timer d=new java.util.Timer();
     private Statement estatuto;
    private ResultSet resultado;
 public Connection s=null;
 
    
    
    
    //CONSTRUCTOR
    public Añadirvuelo() {
        
        initComponents();
        this.setAlignmentX(1000);
            f.conectorBD();
    }

    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        origen = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        destino = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numerov = new javax.swing.JTextField();
        año = new javax.swing.JSpinner();
        mes = new javax.swing.JSpinner();
        dia = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hora = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 255));
        setPreferredSize(new java.awt.Dimension(312, 340));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        origen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BLA", "BRM", "BNS", "CBL", "CCS", "CUM", "VIG", "LFR", "LSP", "LRV", "MAR", "MUN", "MYC", "PMV", "PBL", "PHV", "PZO", "SFD", "SOM", "STD", "TUV", "VLN" }));
        origen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origenActionPerformed(evt);
            }
        });
        add(origen, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 121, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fecha Y Hora Del Vuelo");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 176, 19));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Destino");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 176, 19));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrar");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 262, -1, 40));

        destino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BLA", "BRM", "BNS", "CBL", "CCS", "CUM", "VIG", "LFR", "LSP", "LRV", "MAR", "MUN", "MYC", "PMV", "PBL", "PHV", "PZO", "SFD", "SOM", "STD", "TUV", "VLN" }));
        add(destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 121, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Origen");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Numero De Vuelo");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 140, -1));

        numerov.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(numerov, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 160, 30));

        año.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2019), Integer.valueOf(2019), null, Integer.valueOf(1)));
        add(año, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 70, -1));

        mes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        dia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jLabel5.setText("Año");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));

        jLabel6.setText("Mes");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, 20));

        jLabel7.setText("Dia");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, 20));

        hora.setModel(new javax.swing.SpinnerNumberModel(1, 1, 24, 1));
        add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jLabel8.setText("Hora");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
          Interfaz nd=new Interfaz(1);
          
        try {
         
        
            estatuto = f.s.createStatement();
            String dato1=this.numerov.getText();
            String dato2=""+this.año.getValue()+"-"+this.mes.getValue()+"-"+this.dia.getValue()+"/"+this.hora.getValue();
            String dato3=(String) this.origen.getSelectedItem();
//             String dato4=(String) this.fecha.getValue();
         String dato4=(String) this.destino.getSelectedItem();
            
         //String Datos="('"+"2323244"+"','"+"sdsdsd"+"','"+"sdsdsd"+"','"+"dffd"+"','"+"12wd"+"');";
           //String Datoss="('identiifcacion, 'franco', 'angel', '03-11-99', '5');";
           
            estatuto.executeUpdate("INSERT INTO Vuelos_Avion VALUES ('"+dato1+"','"+dato2+"','"+dato3+"','"+dato4+"')");
           
               
            JOptionPane.showMessageDialog(this,"DATOS REGISTRADOS EXITOSAMENTE");
           nd.cargartabla1();
      
        } catch (SQLException ex) {
            
             JOptionPane.showMessageDialog(this,"LOS DATOS NO SE PUDIERON REGISTRAR verique que efectivamente esta ingresando los datos de manera correcta");
            
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }      
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void origenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_origenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner año;
    public javax.swing.JComboBox destino;
    private javax.swing.JSpinner dia;
    private javax.swing.JSpinner hora;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner mes;
    private javax.swing.JTextField numerov;
    public javax.swing.JComboBox origen;
    // End of variables declaration//GEN-END:variables
}
